services:

  bounty-intel:
    build: .
    image: bounty-intel:latest
    container_name: bounty-intel
    entrypoint: ["sh", "/usr/src/app/scripts/start.sh"]
    working_dir: /usr/src/app
    env_file:
      - .env
    volumes:
      - .:/usr/src/app
    networks:
      - infra-net
    restart: unless-stopped


networks:
  infra-net:
    # Owned/created by the infra-hub compose stack (../infra-hub).
    name: infra-net
    external: true
